### ISSUE TITLE
Error: There must be as many parameter starting bounds as there are parameters

### ISSUE THREAD

**Issue by aboktif** [padpadpadpad/nls.multstart#13]
Hello, 
First I would like to thank you for this great work . 
I am trying to use nls.multstart to fit sine like curve, but I getting error that "There must be as many parameter starting bounds as there are parameters". I double checked all parameters and they are same as the bounds parameters. Below is my function and code I used:

As you can see below, I am trying to fit OPT vs. Volts. The fitting parameters are six:  p1, beta1, beta2, eta, ntot , sig 
The actual data has multiple sets/sites of  similar data shown below, that is why I want to use your function which supports multiple starting values.
Is it too many parameters to fit and that is why it fails? Is it possible to make this fitting happen ?  Could you please help me to make this working ? 

Thank you 
Abdo

## function to fit 

mzmfunc <- function(p1, beta1, beta2, eta, ntot , sig , Volt1, Volt2,lamb) { 
   
    l<-0.63e-2
    co_mod<- 1
    capperl<-0.26e-9
    cap <- capperl*l*co_mod
    vbi_va <- 0.4
    m_va <- 0.3
    mgrad <- (1.0/m_va) - 2.0
    qo <- -1*((mgrad+2)/(mgrad+1))*exp(log(vbi_va)/(mgrad+2))*cap
    qt <- qo*exp(((mgrad+1)/(mgrad+2))*log(vbi_va))
    ntotperl <- 2.34e-9
    ntoti <- ntotperl*l*co_mod*co_mod
    qcap1<- qt*exp(((mgrad+1)/(mgrad+2))*log(1- Volt1/vbi_va))
    phi1<- (-2*pi/lamb)*eta*qcap1
    qcap2<- qt*exp(((mgrad+1)/(mgrad+2))*log(1- Volt2/vbi_va))
    phi2<- (-2*pi/lamb)*eta*qcap2
   
    A1<- sqrt(abs(p1*( 1-sig*(ntot+qcap1))))
    A2<- sqrt(abs(p1*( 1-sig*(ntot+qcap2))))
    Eo1<- -1i*0.5*( A1*exp(-1i*(phi1+beta1)) + A2*exp(-1i*(phi2+beta2)) )
    Eo2<- 0.5*( A1*exp(-1i*(phi1+beta1)) - A2*exp(-1i*(phi2+beta2)) )
    pow1<- abs(Eo1*Conj(Eo1))
    pow2<- abs(Eo2*Conj(Eo2))
    return(pow1)

 }
## using nls_multstart

result1 <- nls_multstart(OPT ~ mzmfunc(p1, beta1, eta, ntot  , sig , Volt1=0, Volt2=Volt, lamb=1.262e-6),
data = sitedata,
iter = 250,
start_lower = c(p1= 0.01, beta1 = 0 , beta2 = 0, eta=1.4e5 , ntot= 1.4742e-11, sig= 1e10 ),
start_upper = c(p1= 0.04, beta1 = 4 , beta2 = 4, eta=10.4e5 , ntot= 10.4742e-11, sig= 10e10 ),
supp_errors = 'Y',
convergence_count = 200,
na.action = na.omit,
lower = c( p1=0.01, beta1 = 0, beta2 = 0, eta=2.4e5,  ntot= 1.4742e-11, sig= 1e10))

##

sitedata
Volt
-4.0  -3.8  -3.6  -3.4  -3.2  -3.0  -2.8  -2.6  -2.4  -2.2  -2.0  -1.8  -1.6  -1.4  -1.2  -1.0 -0.8  -0.6  -0.4  -0.2   0.0
OPT
0.005701643  0.006880183  0.008212966  0.009582967  0.011132687  0.012385114  0.013740420 0.014845677  0.016180800  0.017108030  0.017901936  0.018365383  0.018365383  0.018395009 0.017926686  0.016900517  0.015848932  0.014197112  0.012705741  0.010514775  0.008077928

**Comment by padpadpadpad** [comment]
Hi aboktif

This error hints that you have not got the same number of estimable parameters in your formula, `OPT ~ mzmfunc(p1, beta1, eta, ntot , sig , Volt1=0, Volt2=Volt, lamb=1.262e-6)`, as in your start_upper, `c(p1= 0.01, beta1 = 0 , beta2 = 0, eta=1.4e5 , ntot= 1.4742e-11, sig= 1e10 )` or start_lower `c(p1= 0.01, beta1 = 0 , beta2 = 0, eta=1.4e5 , ntot= 1.4742e-11, sig= 1e10 )`.

Having a play myself you just need to put `beta2` in your formula part as its currently missing. Otherwise it works fine.

Will close this issue now. hope this helps.

```r
# nls.multstart help

# load packages
library(nls.multstart)
library(ggplot2)
library(tibble)

# custom function
mzmfunc <- function(p1, beta1, beta2, eta, ntot , sig , Volt1, Volt2,lamb) {
  
  l<-0.63e-2
  co_mod<- 1
  capperl<-0.26e-9
  cap <- capperl*l*co_mod
  vbi_va <- 0.4
  m_va <- 0.3
  mgrad <- (1.0/m_va) - 2.0
  qo <- -1*((mgrad+2)/(mgrad+1))*exp(log(vbi_va)/(mgrad+2))*cap
  qt <- qo*exp(((mgrad+1)/(mgrad+2))*log(vbi_va))
  ntotperl <- 2.34e-9
  ntoti <- ntotperl*l*co_mod*co_mod
  qcap1<- qt*exp(((mgrad+1)/(mgrad+2))*log(1- Volt1/vbi_va))
  phi1<- (-2*pi/lamb)*eta*qcap1
  qcap2<- qt*exp(((mgrad+1)/(mgrad+2))*log(1- Volt2/vbi_va))
  phi2<- (-2*pi/lamb)*eta*qcap2
  
  A1<- sqrt(abs(p1*( 1-sig*(ntot+qcap1))))
  A2<- sqrt(abs(p1*( 1-sig*(ntot+qcap2))))
  Eo1<- -1i*0.5*( A1*exp(-1i*(phi1+beta1)) + A2*exp(-1i*(phi2+beta2)) )
  Eo2<- 0.5*( A1*exp(-1i*(phi1+beta1)) - A2*exp(-1i*(phi2+beta2)) )
  pow1<- abs(Eo1*Conj(Eo1))
  pow2<- abs(Eo2*Conj(Eo2))
  return(pow1)
}

# create dataframe
Volt = '-4.0 -3.8 -3.6 -3.4 -3.2 -3.0 -2.8 -2.6 -2.4 -2.2 -2.0 -1.8 -1.6 -1.4 -1.2 -1.0 -0.8 -0.6 -0.4 -0.2 0.0'
OPT = '0.005701643 0.006880183 0.008212966 0.009582967 0.011132687 0.012385114 0.013740420 0.014845677 0.016180800 0.017108030 0.017901936 0.018365383 0.018365383 0.018395009 0.017926686 0.016900517 0.015848932 0.014197112 0.012705741 0.010514775 0.008077928'

site_data <- tibble(Volt = as.numeric(unlist(strsplit(Volt, split = ' '))),
                    OPT = as.numeric(unlist(strsplit(OPT, split = ' '))))

# try plotting function
plot(mzmfunc(p1 = 0.02, beta1 = 1, beta2 = 2, eta = 5.4e5, ntot = 5.4742e-11, sig = 5e10, Volt1 = 0, Volt2 = site_data$Volt, lamb = 1.262e-6) ~ site_data$Volt)

# run nls.multstart
result1 <- nls_multstart(OPT ~ mzmfunc(p1, beta1, beta2, eta, ntot, sig , Volt1 = 0, Volt2 = Volt, lamb = 1.262e-6),
                         data = site_data,
                         iter = 250,
                         start_lower = c(p1 = 0.01, beta1 = 0 , beta2 = 0, eta = 1.4e5 , ntot = 1.4742e-11, sig = 1e10),
                         start_upper = c(p1 = 0.04, beta1 = 4 , beta2 = 4, eta = 10.4e5 , ntot = 10.4742e-11, sig = 10e10),
                         supp_errors = 'Y',
                         convergence_count = 200,
                         na.action = na.omit,
                         lower = c(p1 = 0.01, beta1 = 0, beta2 = 0, eta = 2.4e5, ntot = 1.4742e-11, sig = 1e10))

result1
 
```

**Comment by aboktif** [comment]
Hi Daiel

Thank you very much for your support!  
It was typo to forget beta2 and it was not missing from my original code.  When I use the function as below, I still get the same error I mentioned last time. " There must be as many parameter starting bounds as there are parameters "
So every thing is still as you have it above except I want to assign lamb every time I call the function as this: 
lam=1.262e-6  
result1 <- nls_multstart(OPT~ mzmfunc(p1, beta1, beta2, eta, ntot, sig , Volt1 = 0, Volt2 = Volt, lamb = lam),
                         data = sitedata,
                         iter = 250,
                         start_lower = c(p1 = 0.01, beta1 = -4 , beta2 = -4, eta = 1.4e5 , ntot = 1.4742e-11, sig = 1e10),
                         start_upper = c(p1 = 0.04, beta1 = 4 , beta2 = 4, eta = 10.4e5 , ntot = 10.4742e-11, sig = 10e10),
                         supp_errors = 'Y',
                         convergence_count = 200,
                         na.action = na.omit,
                         lower = c(p1 = 0.01, beta1 = 0, beta2 = 0, eta =0, ntot = 0, sig = 0))


Also, can comment on these points please.

- If I put  supp_errors = 'N', I get too many errors as this 

Error in nlsModel(formula, mf, start, wts) : 
  singular gradient matrix at initial parameter estimates

Do you think those error can be ignored and will not affect on the result? 

- When I assign supp_errors = 'Y', yes I get results but I get different results/fitting parameters when I run nls_multstart multiple times with exact inputs. 
Please try it, do you think this fit can have multiple solutions. 

Thank you 
Abdo

**Comment by mathesong** [comment]
I can definitely help here!  

# Options

If you specify data, the function will read everything out of the data input.  If you do not specify data, the function will read everything out of the environment.  So you have two options: 

1. **You put lam into the data input**

This is the best option, as it ensures that everything is in a self-contained unit.  It's just tricky with a data.frame, but what's important to realise is that a data.frame is just a special case of a list.  The nls.multstart package happily accepts lists (see example below).

2. **You let the function pull it out of the environment without specifying a data argument.**

This works, but you just ought to be careful about what you call stuff in the environment.  If the function finds stuff there with the same name, it'll just throw it into the function.

I've provided examples below.


# Examples

## Setting everything up



    # load packages
    library(nls.multstart)
    library(tidyverse)

    # custom function
    mzmfunc <- function(p1, beta1, beta2, eta, ntot , sig , Volt1, Volt2,lamb) {

      l<-0.63e-2
      co_mod<- 1
      capperl<-0.26e-9
      cap <- capperl*l*co_mod
      vbi_va <- 0.4
      m_va <- 0.3
      mgrad <- (1.0/m_va) - 2.0
      qo <- -1*((mgrad+2)/(mgrad+1))*exp(log(vbi_va)/(mgrad+2))*cap
      qt <- qo*exp(((mgrad+1)/(mgrad+2))*log(vbi_va))
      ntotperl <- 2.34e-9
      ntoti <- ntotperl*l*co_mod*co_mod
      qcap1<- qt*exp(((mgrad+1)/(mgrad+2))*log(1- Volt1/vbi_va))
      phi1<- (-2*pi/lamb)*eta*qcap1
      qcap2<- qt*exp(((mgrad+1)/(mgrad+2))*log(1- Volt2/vbi_va))
      phi2<- (-2*pi/lamb)*eta*qcap2

      A1<- sqrt(abs(p1*( 1-sig*(ntot+qcap1))))
      A2<- sqrt(abs(p1*( 1-sig*(ntot+qcap2))))
      Eo1<- -1i*0.5*( A1*exp(-1i*(phi1+beta1)) + A2*exp(-1i*(phi2+beta2)) )
      Eo2<- 0.5*( A1*exp(-1i*(phi1+beta1)) - A2*exp(-1i*(phi2+beta2)) )
      pow1<- abs(Eo1*Conj(Eo1))
      pow2<- abs(Eo2*Conj(Eo2))
      return(pow1)
    }

    # create dataframe
    Volt = '-4.0 -3.8 -3.6 -3.4 -3.2 -3.0 -2.8 -2.6 -2.4 -2.2 -2.0 -1.8 -1.6 -1.4 -1.2 -1.0 -0.8 -0.6 -0.4 -0.2 0.0'
    OPT = '0.005701643 0.006880183 0.008212966 0.009582967 0.011132687 0.012385114 0.013740420 0.014845677 0.016180800 0.017108030 0.017901936 0.018365383 0.018365383 0.018395009 0.017926686 0.016900517 0.015848932 0.014197112 0.012705741 0.010514775 0.008077928'

    site_data <- tibble(Volt = as.numeric(unlist(strsplit(Volt, split = ' '))),
                        OPT = as.numeric(unlist(strsplit(OPT, split = ' '))))



### Alternative 1: Recommended

    site_data_list <- as.list(site_data)
    site_data_list$lam = 1.262e-6


    result1 <- nls_multstart(OPT~ mzmfunc(p1, beta1, beta2, eta, ntot, sig , Volt1 = 0, Volt2 = Volt, lamb = lam),
                             data = site_data_list,
                             iter = 250,
                             start_lower = c(p1 = 0.01, beta1 = -4 , beta2 = -4, eta = 1.4e5 , ntot = 1.4742e-11, sig = 1e10),
                             start_upper = c(p1 = 0.04, beta1 = 4 , beta2 = 4, eta = 10.4e5 , ntot = 10.4742e-11, sig = 10e10),
                             supp_errors = 'Y',
                             convergence_count = 200,
                             na.action = na.omit,
                             lower = c(p1 = 0.01, beta1 = 0, beta2 = 0, eta =0, ntot = 0, sig = 0))
 
    ## For some reaon, I get warnings about na.action, but you can



### Alternative 2: Works, but not recommended, as you can run into problems


    lam <- 1.262e-6
    Volt <- site_data$Volt
    OPT <- site_data$OPT

    result2 <- nls_multstart(OPT~ mzmfunc(p1, beta1, beta2, eta, ntot, sig , Volt1 = 0, Volt2 = Volt, lamb = lam),
                             iter = 250,
                             start_lower = c(p1 = 0.01, beta1 = -4 , beta2 = -4, eta = 1.4e5 , ntot = 1.4742e-11, sig = 1e10),
                             start_upper = c(p1 = 0.04, beta1 = 4 , beta2 = 4, eta = 10.4e5 , ntot = 10.4742e-11, sig = 10e10),
                             supp_errors = 'Y',
                             convergence_count = 200,
                             na.action = na.omit,
                             lower = c(p1 = 0.01, beta1 = 0, beta2 = 0, eta =0, ntot = 0, sig = 0))




## Also, when I run this, the outcomes look ok!

    result1
    #> Nonlinear regression model
    #>   model: OPT ~ mzmfunc(p1, beta1, beta2, eta, ntot, sig, Volt1 = 0, Volt2 = Volt,     lamb = lam)
    #>    data: data
    #>        p1     beta1     beta2       eta      ntot       sig 
    #> 1.726e-02 1.123e+04 1.123e+04 1.798e+05 1.510e-12 2.480e+11 
    #>  residual sum-of-squares: 2.109e-07
    #> 
    #> Number of iterations to convergence: 64 
    #> Achieved convergence tolerance: 1.49e-08

    # get predictions
    preds <- broom::augment(result1)

    # plot predictions
    ggplot(preds) +
      geom_point(aes(Volt, OPT)) +
      geom_line(aes(Volt, .fitted), col = 'red')

![](https://i.imgur.com/kBK4ni9.png)

Created on 2018-06-14 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by aboktif** [comment]
Thank you Daniel & Granville, this is really helpful !
Best,
Abdo

**Comment by aboktif** [comment]
Hi Daniel & Granville

Thank you for your help ! I have to issues: 
- Every time I call nls_multstart, I get different results for the fitting parameters on the same exact data. How can I get this fixed and get all time similar results for the fitting parameters ( eta  , ntotperl , sig ).

- As you see from the image below, I am fitting two data (blueData, redData) and get the fitting parameters for each. I was expecting I get similar fitting parameters for (eta  , ntotperl , sig) for both data. As you see in the image, those two curves very similar except they are pi phase shifted from one another. 
- I noticed the fitting sometimes takes the value I assigned in 'lower' in nls_multstart function as shown in the image below , ntotperl=0.00e+00
For both data (blueData, redData), the expected values for (eta  , ntotperl , sig) are eta =~ 2.40e5, ntotperl =~ 2.34e-9, sig = ~8.0e10 and they could be different but they need to be consistent every time I run nls_multstart
For beta1 and beta2 they are random phase or angels in radiance and they can take any values. 

Here are the data, function , and nls_multstart input parametrs
your help is really appreciated 

Thank you 
Abdo

sitedata

blueData:
  0.0029621019 0.0031441264 0.0033358000 0.0034986460 0.0036702868 0.0038132915 0.0039111097 0.0040373835 0.0040803743 0.0040709897 0.0040105137 0.0038815037 0.0036576319 0.0034387452 0.0031434025 0.0028047877 0.0023944182 0.0019696996 0.0015332042 0.0011084089 0.0007231027 0.0003991168 0.0001695899 0.0000978363
redData:
  1.298375e-03 1.122535e-03 9.253372e-04 7.426770e-04 5.618236e-04 3.994846e-04 2.674853e-04 1.632676e-04 1.043999e-04 9.799412e-05 1.429881e-04 2.435567e-04 4.067242e-04 6.214411e-04 8.943345e-04 1.213109e-03 1.571810e-03 1.957492e-03 2.328627e-03 2.716439e-03 3.082478e-03 3.345800e-03 3.505097e-03 3.535086e-03
Volt:
  -4.6 -4.4 -4.2 -4.0 -3.8 -3.6 -3.4 -3.2 -3.0 -2.8 -2.6 -2.4 -2.2 -2.0 -1.8 -1.6 -1.4 -1.2 -1.0 -0.8 -0.6 -0.4 -0.2  0.0  
lam:
  1264

custom function
mzmfunc <- function(p1, beta1, beta2, eta, ntotperl , sig , Volt1, Volt2,lamb) {

lamb<- lamb*1e-9
l<-0.63e-2
co_mod<- 1
capperl<-0.26e-9
cap <- capperl*l*co_mod
vbi_va <- 0.4
m_va <- 0.3
mgrad <- (1.0/m_va) - 2.0
qo <- -1*((mgrad+2)/(mgrad+1))*exp(log(vbi_va)/(mgrad+2))*cap
qt <- qo*exp(((mgrad+1)/(mgrad+2))*log(vbi_va))
ntot <- ntotperl*l*co_mod*co_mod
qcap1<- qt*exp(((mgrad+1)/(mgrad+2))*log(1- Volt1/vbi_va))
phi1<- (-2*pi/lamb)*eta*qcap1
qcap2<- qt*exp(((mgrad+1)/(mgrad+2))*log(1- Volt2/vbi_va))
phi2<- (-2*pi/lamb)*eta*qcap2  
A1<- sqrt(abs(p1*( 1-sig*(ntot+qcap1))))
A2<- sqrt(abs(p1*( 1-sig*(ntot+qcap2))))
Eo1<- -1i*0.5*( A1*exp(-1i*(phi1+beta1)) + A2*exp(-1i*(phi2+beta2)) )
Eo2<- 0.5*( A1*exp(-1i*(phi1+beta1)) - A2*exp(-1i*(phi2+beta2)) )
pow1<- abs(Eo1*Conj(Eo1))
pow2<- abs(Eo2*Conj(Eo2))
return(pow1)

}

result1 <- nls_multstart(OPT~ mzmfunc( p1, beta1, beta2, eta, ntotperl, sig , Volt1 = 0, Volt2 = Volt, lamb =lam),
                           data = sitedata,
                           iter = 1000,
                           start_lower = c(p1 = amp_meas , beta1 = 0, beta2 = 0, eta = 0 , ntotperl = 0, sig = 0),
                           start_upper = c(p1 = amp_meas , beta1 = 2*pi, beta2 = 2*pi, eta = 3e5 , ntotperl = 1e-9, sig =10e10),
                           supp_errors = 'Y',
                           convergence_count = 300,
                           na.action = na.omit,
                           lower = c(p1 = 0.0001,beta1=0, beta2 = 0, eta =0, ntotperl = 0, sig = 0))
 


![image](https://user-images.githubusercontent.com/598125/41671645-c0d3a690-7485-11e8-904e-6c844c3d55c9.png)
