### ISSUE TITLE
New version of tidyr::nest

### ISSUE THREAD

**Issue by mathesong** [padpadpadpad/nls.multstart#15]
I updated my tidyr the other day, and I get a warning every time I run nls_multstart.

```
Warning message:
All elements of `...` must be named.
```

This relates to the new syntax of the tidyr nest() command.  I'll submit a PR to fix this.

**Update**: PR https://github.com/padpadpadpad/nls.multstart/pull/16

**Comment by padpadpadpad** [comment]
Hi @mathesong. Have been meaning to do this for a while so thanks for making a PR. Should probably change the README and consider doing another CRAN submission.

Hope you are keeping safe.
